Feature/devise auth
lenkton/TestGuru pull request #10
Opened 2021-01-13 11:46 UTC by lenkton

Added authentication mechanics with the admin and ordinary user roles

2021-01-13 13:01 UTC, VidgarVii requested changes

2021-01-13 13:01 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +  def find_test
и этим мы ломаем создание вопроса

2021-01-13 13:01 UTC, VidgarVii commented on app/controllers/admin/tests_controller.rb
> +    @test.author = current_user
@test = current_user.tests.new(test_params)

2021-01-13 13:01 UTC, VidgarVii commented on app/models/user.rb
>    has_many :tests, foreign_key: :author_id, dependent: :destroy
в бд у тебя всё хорошо. author_id
А в моделе устроил путаницу

2021-01-14 09:16 UTC, lenkton commented on app/models/user.rb
>    has_many :tests, foreign_key: :author_id, dependent: :destroy
А как можно сделать лучше?
Удалил сообщения к валидациям, но как сделать код ещё более понятным я не вижу

2021-01-14 17:00 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +  def is_admin?
как-то не по ООП, У кого спрашиваешь?
будет логичней. current_user.admin?

2021-01-14 17:00 UTC, VidgarVii commented on app/models/user.rb
>    has_many :tests, foreign_key: :author_id, dependent: :destroy
обозвать как нить own_tests например. Главное чтобы было понятно, что за тесты без гадалок

2021-01-15 22:11 UTC, merged