Feature/badges
lenkton/TestGuru pull request #14
Opened 2021-02-01 16:10 UTC by lenkton

Added mechanics for badge creating (for admins) and badge acquiring (for users)

2021-02-01 17:09 UTC, VidgarVii requested changes

2021-02-01 17:09 UTC, VidgarVii commented on db/seeds.rb
> +      {name: 'Badge for certain tests', image_url: "http://localhost:3000/smile.bmp", condition: set_of_tests_solved_conditions[0]},
так каких тестов?

2021-02-01 17:09 UTC, VidgarVii commented on db/seeds.rb
> +    ],
по ДЗ заданы 3 условия. Многие студенты делают больше

2021-02-01 17:09 UTC, VidgarVii commented on db/seeds.rb
> +end
честно говоря в сидах намудрил. Очень сложно читается. Стандартный синтаксис rails в разы лучше

2021-02-01 17:09 UTC, VidgarVii commented on app/controllers/test_taking_sessions_controller.rb
> +    check_badges_for(@session.user)
награду как правило выдают после прохождения теста, а не при просмотре результата. Тем более этот результат можно посмотреть в любое время.

2021-02-01 17:09 UTC, VidgarVii commented on app/controllers/test_taking_sessions_controller.rb
> +            end
1 это не задача контроллера.
2 это какая-то помесь ФП и императивности и с нарушением SRP (SOLID)
3 контент надо держать в файлах локали

2021-02-01 17:09 UTC, VidgarVii commented on app/helpers/badge_helper.rb
> +    return 'not-possessed' unless badge.rewarded_users.include?(current_user)
весь контент должен быть в локале

2021-02-01 17:09 UTC, VidgarVii commented on app/models/set_of_tests_solved_condition.rb
> +end
инкапсулируй всё логику условий для выдачи наград в сервисы. Не надо такое хранить в БД.
Как будешь выкручиваться если надо будет создать 10, 100, 1000 условий лоя ачивок?
В БД можно держать только физические свойства награды. Имя, картинка, правило и .т.д.

2021-02-03 10:38 UTC, lenkton commented on app/models/set_of_tests_solved_condition.rb
> +end
Я, кажется, слабо понимаю, что вы предлагаете сделать.
Из той ситуации, где я сейчас нахожусь, выглядит странным отделять логику проверки выполнения условия от самого условия. Вы же не хотите, чтобы я оставил всё как есть, но перенёс методы met_for? из моделек в новый сервис, где огромный case будет пробегаться по классам моделек и для каждой вызывать свою функцию, которая просто будет уже иметь уникальное название.

2021-02-05 06:41 UTC, VidgarVii requested changes

2021-02-05 06:41 UTC, VidgarVii commented on app/controllers/test_taking_sessions_controller.rb
> +      flash[:notice] = NewBadgesNotificationService.call(@session)
сложновато с NewBadgesNotificationService и лишние запросы в бд ни к чему. Новые награды можно было получить у BadgesGrantingService

2021-02-05 06:41 UTC, VidgarVii commented on app/services/badges_granting_service.rb
> +
```
CONDITIONS = {
  tries_count: TriesCountConditionSpecification,
  category: CategoryConditionSpecification,
  level: LevelConditionSpecification
}.freeze
```

2021-02-05 06:41 UTC, VidgarVii commented on app/services/category_condition_specification.rb
> +    Category.find_by(id: @parameter).tests - @session.user.test_taking_sessions.successful.map(&:test) == []
Думай декларативно
Test.joins(...).where(...).exists?

2021-02-05 06:41 UTC, VidgarVii commented on app/services/tries_count_condition_specification.rb
> +end
Везде думай декларативно
Спецификации это уже не паттерн service object. Хорошо бы их выделить в отдельной директории specifications

2021-02-05 06:41 UTC, VidgarVii commented on app/views/admin/badges/show.html.slim
> +=< link_to 'Back', admin_badges_path
весь контент надо хранить в файлах локали, чтобы можно было безболезненно переключать локаль + стандартизация

2021-02-05 19:17 UTC, VidgarVii requested changes

2021-02-05 19:17 UTC, VidgarVii commented on config/routes.rb
> +  resources :conditions
у тебя нет такого контроллера и вряд ли появится.

2021-02-05 19:17 UTC, VidgarVii commented on app/services/specifications/abstract_condition_specification.rb
> +end
Спецификация это не сервис. Путь должен быть app/specifications/

2021-02-05 19:17 UTC, VidgarVii commented on app/services/badges_granting_service.rb
> +      condition = CONDITIONS[badge.condition_type.to_sym].new(session, badge.condition_parameter)
если за рание привести ключи к единому виду то to_sym не понадобиться

2021-02-05 19:17 UTC, VidgarVii commented on app/services/badges_granting_service.rb
> +      badge.grant_to(session.user) if (condition.satisfies?)
if condition.satisfies?

2021-02-05 19:17 UTC, VidgarVii commented on app/services/badges_granting_service.rb
> +  end
не вижу чтобы данный метод использовался

2021-02-05 19:17 UTC, VidgarVii commented on app/services/badges_granting_service.rb
> +require_relative './specifications/tries_count_condition_specification'
если использовал require_relative, значит что-то не так

2021-02-05 19:17 UTC, VidgarVii commented on app/services/specifications/category_condition_specification.rb
> +    return if Category.find_by(id: @parameter) != @session.test.category
методы предикаты должны возвращать только 2 значения true или false

2021-02-05 19:17 UTC, VidgarVii commented on app/services/badges_granting_service.rb
> +    @new_badges
тут будет всегда нил

2021-02-05 19:17 UTC, VidgarVii commented on app/services/specifications/category_condition_specification.rb
> +  end
тут явно ошибка. И не одна....

у меня как то так получилось
```
  def satisfies?
    return false if Category.find(@parameter) != @session.test.category

    tests = Test.of_category(Category.find(@parameter).name)
    tests.size == passed_tests(tests).size
  end
  
  private

  def passed_tests(tests)
    Test
      .joins(:test_taking_sessions)
      .where(test_taking_sessions: { user: @session.user, success: true })
      .merge(tests)
      .uniq
  end
```

2021-02-06 18:30 UTC, VidgarVii requested changes

2021-02-06 18:30 UTC, VidgarVii commented on app/controllers/test_taking_sessions_controller.rb
> +
чаще всего эти строчки сокращают. BadgesGrantingService.new(@session).call 
или BadgesGrantingService.call(@session)
или BadgesGrantingService.call(session: @session)

честно говоря session не очень хорошее название. Так как его застолбило rails

2021-02-06 18:30 UTC, VidgarVii commented on app/helpers/badge_helper.rb
> +  def possessed?(badge)
не понял, кто тут рехнулся?

2021-02-06 18:30 UTC, VidgarVii commented on app/models/badge.rb
> +  end
сомнительное решение класть сюда данный метод. Тут скорей можно трактовать смысл, что ты баджу дарешь юзера...

Я бы оставил этот метод в сервисе, который выдаёт бадж

2021-02-06 18:30 UTC, VidgarVii commented on app/specifications/category_condition_specification.rb
> +end
учитывая, что все эти спецификации относятся к баджикам. Я бы их всех положил в модуль Badges

2021-02-06 18:30 UTC, VidgarVii commented on app/specifications/category_condition_specification.rb
> +end
копипастнул под чистую мой код. А он точно работает? Надеюсь проверил и разобрался что тут вообще происходит

2021-02-06 18:30 UTC, VidgarVii commented on app/specifications/category_condition_specification.rb
> +end
я бы еще добавил предусловие на наличие данной награды и юзера. Если уже есть награда, то смысла выдавать еще раз нет

2021-02-06 18:30 UTC, VidgarVii commented on app/specifications/level_condition_specification.rb
> +  end
.empty? вместо == []

2021-02-06 18:30 UTC, VidgarVii commented on app/specifications/level_condition_specification.rb
> +  end
всё что после && можно инкапуслировать в метод, для улучшения читаемости. А то что тут вообще происходит сразу не понятно

2021-02-06 18:30 UTC, VidgarVii commented on app/specifications/tries_count_condition_specification.rb
> +    end && tries_for_last_test.size.equal?(@parameter.to_i)
end && ...
так вообще не надо делать.
Разбивай не методы

2021-02-06 18:30 UTC, VidgarVii commented on app/specifications/tries_count_condition_specification.rb
> +
```
tries_for_last_test = 
  @session.user.test_taking_sessions.where('test_taking_sessions.test_id = ?', @session.test.id)
```

2021-02-06 18:30 UTC, VidgarVii commented on app/specifications/tries_count_condition_specification.rb
> +
или
```
tries_for_last_test = 
  @session
    .user
    .test_taking_sessions
    .where('test_taking_sessions.test_id = ?', @session.test.id)
```

2021-02-06 18:30 UTC, VidgarVii commented on app/specifications/tries_count_condition_specification.rb
> +
не все команды поддерживают многострочный код, так как его сложно копипастить в консоль. Но за то читается хорошо

2021-02-06 18:30 UTC, VidgarVii commented on app/specifications/tries_count_condition_specification.rb
> +    end && tries_for_last_test.size.equal?(@parameter.to_i)
.all?(&:condition?)

2021-02-06 18:30 UTC, VidgarVii commented on app/views/shared/_header.html.slim
>      = link_to "to admin's", admin_tests_path
вложенные условия или блоки всегда плохо
Да и тут вообще можно спокойно сократить в 1 строку
if user_signed_in? && current_user.admin?
или
if current_user&.admin?

2021-02-06 19:03 UTC, lenkton commented on app/controllers/test_taking_sessions_controller.rb
> +
Дело в том, что мне потом в 16й строчке нужен этот экземпляр сервиса, чтобы получить список бейджиков, которые выдал сервис во время последнего своего вызова, а делать вот такую вещь мне показалось некрасиво:
(badges_service = BadgesGrantingService.new(@session)).call

Впрочем, может мне тогда интерфейс сервиса как-нибудь поменять?

2021-02-08 16:10 UTC, merged