Feature/questions controllers
lenkton/TestGuru pull request #6
Opened 2020-12-15 14:40 UTC by lenkton

2020-12-15 16:50 UTC, VidgarVii requested changes

2020-12-15 16:50 UTC, VidgarVii commented on config/routes.rb
> +    resources :questions
будет удобней работать если добавить shallow: true

2020-12-15 16:50 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    question = Question.find(params[:id].to_i)
to_i не нужен

2020-12-15 16:50 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  attr_accessor :test
точно не attr_accessor. Да и так не пишут. Не rails way
у тебя уже есть before_action для получения переменной

2020-12-15 16:50 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  end
1. ни каких q
2. нужен strong_params http://rusrails.ru/action-controller-overview#strong-parameters
3. проверяй создание ресурса 
```
if @question.save
  redirect_to @question
else
  render :new
end

```

2020-12-16 16:03 UTC, VidgarVii requested changes

2020-12-16 16:03 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    question = Question.new(question_params)
question у тебя локальная переменная.
А нужна инстанс, чтобы её увидела представление

2020-12-16 16:03 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    Question.find(params[:id]).destroy
у тебя строчка Question.find(params[:id]) 2 раза. Вынеси получение вопроса в метод.
Можно так же засунуть метод в before_action

2020-12-16 16:03 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  end
тут должен остаться только params.require(:question).permit(:text)

2020-12-16 16:03 UTC, VidgarVii commented on config/routes.rb
> +  resources :tests, shallow: true do
промахнулся с shallow: true
почитай http://rusrails.ru/rails-routing#melkoe-vlozhenie

2020-12-16 16:56 UTC, lenkton commented on app/controllers/questions_controller.rb
> +    question = Question.new(question_params)
А зачем это надо?

2020-12-16 16:57 UTC, lenkton commented on config/routes.rb
> +  resources :tests, shallow: true do
Но там написано, что так тоже можно! Я ведь подобным материалом и руководствовался. Почему так не стоит делать?

2020-12-16 17:21 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @question = Question.new(question_params)
@question = @test.questions.new(question_params)

2020-12-16 17:23 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    question = Question.new(question_params)
чтобы её увидела представление.

2020-12-16 17:25 UTC, VidgarVii commented on config/routes.rb
> +  resources :tests, shallow: true do
да можно и так. Но такие практики 'Для всех' часто выходят боком. Хотя на 1 взгляд вроде всё должно быть нормально

2020-12-16 22:45 UTC, merged