Feature/basic views
lenkton/TestGuru pull request #7
Opened 2020-12-21 12:01 UTC by lenkton

Added some veiws, patrials, upgraded controllers.
Added controls, added basic layout.

2020-12-21 12:29 UTC, VidgarVii requested changes

2020-12-21 12:29 UTC, VidgarVii commented on Gemfile
> +gem 'slim'
лучше взять рельсовую версию gem 'slim-rails'
и настроить автогенератор файлов
```
config.generators do |g|
  g.template_engine :slim
end
```

2020-12-21 12:29 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    redirect_to @test
зачем тут редирект? можно же просто удалить экшен

2020-12-21 12:29 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @test = @question.test
1. как инстанс переменная ни как не используется. Лучше сделать её локальной
2. Так как объект @question после удаления в памяти еще останется, можно к нему обратиться и вытащить тест

2020-12-21 12:29 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  before_action :find_test, only: :show
ради 1 экшена целый колбек будет слишком жирно. И явное определение данных всегда лучше

2020-12-21 12:29 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +    Time.now.year
https://github.com/rubocop-hq/rails-style-guide#time-now

2020-12-21 12:29 UTC, VidgarVii commented on app/views/layouts/application.slim
> +
футер стоит убрать в отдельный партиал

2020-12-21 12:29 UTC, VidgarVii commented on app/views/layouts/application.slim
> +      p Created with the help of #{link_to 'Thinknetica', 'https://thinknetica.com/'}
внешние ссылки стоит открывать в новой вкладке и иметь опцию ....

2020-12-21 12:29 UTC, VidgarVii commented on app/views/questions/edit.slim
> +== link_to 'Back to questions', test_questions_path(@question.test)
хватит одного знака =
http://slim-lang.com/

2020-12-21 15:44 UTC, VidgarVii requested changes

2020-12-21 15:44 UTC, VidgarVii commented on app/views/layouts/_footer.slim
> +p Created with the help of #{link_to 'Thinknetica', 'https://thinknetica.com/', rel: "nofollow", target: "_blank"}
футер правильно положить в `shared`, а не в `layouts`

2020-12-21 15:44 UTC, VidgarVii commented on app/views/layouts/application.slim
> +    == csrf_meta_tags
достаточно 1 знака =. я об этом уже писал
только в при вызове блока ==. По моему это связано с экранированием тегов

2020-12-21 15:44 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +    Time.zone.now.year
Time.current.year

2020-12-21 18:59 UTC, VidgarVii commented on app/views/shared/_footer.slim
> +  #{link_to 'TestGuru', github_url('lenkton', 'TestGuru'), rel: "nofollow", target: "_blank"}
должен остаться только один =)
= github_url('lenkton', 'TestGuru')

2020-12-21 18:59 UTC, VidgarVii commented on app/views/shared/_footer.slim
> +p Created with the help of #{link_to 'Thinknetica', 'https://thinknetica.com/', rel: "nofollow", target: "_blank"}
еще можно так
rel: :nofollow, target: :_blank

2020-12-21 18:59 UTC, VidgarVii commented on app/views/tests/show.slim
> += link_to 'Add a question', new_test_question_path(@test)
следи, чтобы в конце файла пустая строка была

2020-12-21 18:59 UTC, VidgarVii commented on app/views/questions/show.slim
> +    ol = render partial: 'answer', collection: @question.answers
= render @question.answers

2020-12-23 13:52 UTC, lenkton commented on app/views/questions/show.slim
> +    ol = render partial: 'answer', collection: @question.answers
Но это ведь не работает, пока не добавлен ресурс ответа со всеми соответствующими представлениями (или же я делаю что-то неправильно). Поэтому пока это и написано в полной форме.
Я в следующей версии хотел добавить ответы, и там бы это смотрелось логично.

2020-12-23 14:00 UTC, merged